DROP DATABASE IF EXISTS rosendb;
CREATE DATABASE rosendb;
USE rosendb;

DROP TABLE IF EXISTS image;
CREATE TABLE image (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dir VARCHAR(2048) NULL,
  name VARCHAR(1024) NULL
);